name: Zip and Upload to Dropbox
author: ETdoFresh
description: Zips a directory and uploads to dropbox

inputs:
  DIRECTORY_TO_ZIP:
    description: Location on Docker to zip
    default: './Build/'
  ZIP_FILENAME:
    description: Filename of the zip
    default: 'Build_DATE.zip'
  DROPBOX_TARGET:
    description: Location in Dropbox (including filename) to place the build zip
    default: '/Build_DATE.zip'
  DROPBOX_TOKEN:
    description: Dropbox App Token
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DIRECTORY_TO_ZIP }}
    - ${{ inputs.ZIP_FILENAME }}
    - ${{ inputs.DROPBOX_TARGET }}
    - ${{ inputs.DROPBOX_TOKEN }}
 