name: Unity 2019.1.14f1 Build and Deploy to Dropbox
author: ETdoFresh
description: Build a Unity Project

inputs:
  UNITY_USERNAME:
    description: Your Unity Username
    required: true
  UNITY_PASSWORD:
    description: Your Unity Password
    required: true
  UNITY_PROJECT_PATH:
    description: Path where the Unity Project is located.
    required: false
    default: '.'
  BUILD_NAME:
    description: Name of your project
    required: true
    default: 'Untitled'
  BUILD_TARGET:
    description: Windows, Linux, OSX, WebGL
    required: true
    default: 'Windows'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BUILD_PATH: Build
    TEST_PLATFORM: linux
    WORKDIR: /root/project
    UNITY_ACTIVATION_FILE: unity3d.alf
    UNITY_LICENSE_FILE: Unity_v2019.x.ulf
  args:
    - ${{ inputs.UNITY_USERNAME }}
    - ${{ inputs.UNITY_PASSWORD }}
    - ${{ inputs.UNITY_PROJECT_PATH }}
    - ${{ inputs.BUILD_NAME }}
    - ${{ inputs.BUILD_TARGET }}

branding:
  color: 'black'
  icon: 'box'
