name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    
    - id: first
      uses: ETdoFresh/Actions/HelloWorld@latest
      with:
        person: 'ETdoFresh'
        
    - id: second
      run: echo "The time was ${{ steps.first.outputs.time }}"
      
    - uses: actions/checkout@v1
    - uses: ETdoFresh/Actions/DummyBuild@latest
    - uses: ETdoFresh/Actions/DockerLs@latest
    - uses: ETdoFresh/Actions/UploadZipToDropbox@latest
      with:
        DROPBOX_TARGET: DummyBuild_DATE.zip
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
    - uses: ETdoFresh/Actions/UploadToGithubPages@latest
      with:
        GITHUB_REPOSITORY: ETdoFresh/Actions
        GITHUB_USERNAME: ${{ secrets.UNITY_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_GEN_TOKEN }}
           
    # - uses: ETdoFresh/Actions/UnityBuild@latest
