name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    
    - id: first
      uses: ETdoFresh/Actions/HelloWorld@master
      with:
        person: 'ETdoFresh'
        
    - id: second
      run: echo "The time was ${{ steps.first.outputs.time }}"
      
    - id: third
      uses: ETdoFresh/Actions/UnityBuild@master
